-- MySQL Script generated by MySQL Workbench
-- Fri Jun  5 12:52:42 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema video_game_market_analysis
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema video_game_market_analysis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `video_game_market_analysis` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `video_game_market_analysis` ;

-- -----------------------------------------------------
-- Table `video_game_market_analysis`.`developers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `video_game_market_analysis`.`developers` (
  `developer_id` INT NOT NULL AUTO_INCREMENT,
  `developer_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`developer_id`),
  UNIQUE INDEX `developer_name` (`developer_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1697
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `video_game_market_analysis`.`genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `video_game_market_analysis`.`genres` (
  `genre_id` INT NOT NULL AUTO_INCREMENT,
  `genre_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`genre_id`),
  UNIQUE INDEX `genre_name` (`genre_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `video_game_market_analysis`.`publishers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `video_game_market_analysis`.`publishers` (
  `publisher_id` INT NOT NULL AUTO_INCREMENT,
  `publisher_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`publisher_id`),
  UNIQUE INDEX `publisher_name` (`publisher_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 584
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `video_game_market_analysis`.`ratings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `video_game_market_analysis`.`ratings` (
  `rating_id` INT NOT NULL AUTO_INCREMENT,
  `rating_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`rating_id`),
  UNIQUE INDEX `rating_name` (`rating_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `video_game_market_analysis`.`games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `video_game_market_analysis`.`games` (
  `game_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `year_of_release` INT NULL DEFAULT NULL,
  `genre_id` INT NULL DEFAULT NULL,
  `publisher_id` INT NULL DEFAULT NULL,
  `developer_id` INT NULL DEFAULT NULL,
  `rating_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`game_id`),
  INDEX `fk_games_genre` (`genre_id` ASC) VISIBLE,
  INDEX `fk_games_publisher` (`publisher_id` ASC) VISIBLE,
  INDEX `fk_games_developer` (`developer_id` ASC) VISIBLE,
  INDEX `fk_games_rating` (`rating_id` ASC) VISIBLE,
  CONSTRAINT `fk_games_developer`
    FOREIGN KEY (`developer_id`)
    REFERENCES `video_game_market_analysis`.`developers` (`developer_id`),
  CONSTRAINT `fk_games_genre`
    FOREIGN KEY (`genre_id`)
    REFERENCES `video_game_market_analysis`.`genres` (`genre_id`),
  CONSTRAINT `fk_games_publisher`
    FOREIGN KEY (`publisher_id`)
    REFERENCES `video_game_market_analysis`.`publishers` (`publisher_id`),
  CONSTRAINT `fk_games_rating`
    FOREIGN KEY (`rating_id`)
    REFERENCES `video_game_market_analysis`.`ratings` (`rating_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13438
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `video_game_market_analysis`.`platforms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `video_game_market_analysis`.`platforms` (
  `platform_id` INT NOT NULL AUTO_INCREMENT,
  `platform_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`platform_id`),
  UNIQUE INDEX `platform_name` (`platform_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `video_game_market_analysis`.`raw_video_game_sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `video_game_market_analysis`.`raw_video_game_sales` (
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `platform` VARCHAR(50) NULL DEFAULT NULL,
  `year_of_release` VARCHAR(20) NULL DEFAULT NULL,
  `genre` VARCHAR(100) NULL DEFAULT NULL,
  `publisher` VARCHAR(255) NULL DEFAULT NULL,
  `na_sales` VARCHAR(20) NULL DEFAULT NULL,
  `eu_sales` VARCHAR(20) NULL DEFAULT NULL,
  `jp_sales` VARCHAR(20) NULL DEFAULT NULL,
  `other_sales` VARCHAR(20) NULL DEFAULT NULL,
  `global_sales` VARCHAR(20) NULL DEFAULT NULL,
  `critic_score` VARCHAR(20) NULL DEFAULT NULL,
  `critic_count` VARCHAR(20) NULL DEFAULT NULL,
  `user_score` VARCHAR(20) NULL DEFAULT NULL,
  `user_count` VARCHAR(20) NULL DEFAULT NULL,
  `developer` VARCHAR(255) NULL DEFAULT NULL,
  `rating` VARCHAR(50) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `video_game_market_analysis`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `video_game_market_analysis`.`sales` (
  `sales_id` INT NOT NULL AUTO_INCREMENT,
  `game_id` INT NOT NULL,
  `platform_id` INT NOT NULL,
  `na_sales` DECIMAL(10,2) NULL DEFAULT NULL,
  `eu_sales` DECIMAL(10,2) NULL DEFAULT NULL,
  `jp_sales` DECIMAL(10,2) NULL DEFAULT NULL,
  `other_sales` DECIMAL(10,2) NULL DEFAULT NULL,
  `global_sales` DECIMAL(10,2) NULL DEFAULT NULL,
  `critic_score` INT NULL DEFAULT NULL,
  `critic_count` INT NULL DEFAULT NULL,
  `user_score` DECIMAL(4,2) NULL DEFAULT NULL,
  `user_count` INT NULL DEFAULT NULL,
  PRIMARY KEY (`sales_id`),
  UNIQUE INDEX `uq_game_platform` (`game_id` ASC, `platform_id` ASC) VISIBLE,
  INDEX `fk_sales_platform` (`platform_id` ASC) VISIBLE,
  CONSTRAINT `fk_sales_game`
    FOREIGN KEY (`game_id`)
    REFERENCES `video_game_market_analysis`.`games` (`game_id`),
  CONSTRAINT `fk_sales_platform`
    FOREIGN KEY (`platform_id`)
    REFERENCES `video_game_market_analysis`.`platforms` (`platform_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
